const DEFAULT_URL_VALUE = 'naver.com';

const DEFAULT_CONTENT_COLOR_VALUE = '#000000';

const DEFAULT_BACKGROUND_COLOR_VALUE = '#FFFFFF';

const DEFAULT_ERROR_CORRECTION_LEVEL_VALUE = 'L';

const DEFAULT_WIDTH_VALUE = '37';

const DEFAULT = {
  URL: DEFAULT_URL_VALUE,
  CONTENT_COLOR: DEFAULT_CONTENT_COLOR_VALUE,
  BACKGROUND_COLOR: DEFAULT_BACKGROUND_COLOR_VALUE,
  ERROR_CORRECTION_LEVEL_VALUE: DEFAULT_ERROR_CORRECTION_LEVEL_VALUE,
  WIDTH: DEFAULT_WIDTH_VALUE,
} as const

const OPTIONS = {
  DEFAULT,
} as const;

export default OPTIONS;
